### ISSUE TITLE
What is the license for the code?

### ISSUE THREAD

**Issue by twolodzko** [bmitc/the-little-schemer#1]
I would like to use the code from your repo as unit tests for a side project, I assume that you published it as public domain, but I would like to confirm if it is ok for you that the code is re-used and released elsewhere under MIT license with providing attribution?

**Comment by bmitc** [comment]
Hello! Thanks for bringing this up. I went ahead and assigned this repository the [MIT No Attribution License (MIT-0)](https://github.com/aws/mit-0) (is also an [OSI approved license](https://opensource.org/licenses/MIT-0)), which is the MIT License but removes the requirement for attribution.

If you think it would be helpful for others to be pointed to this repository and you want, feel free to simply point to this repository. Otherwise, there's no need to worry about copying the license or attributing.

Out of curiosity, what is your side project if you're able and willing to share?

**Comment by twolodzko** [comment]
Thanks. Oh, I forgot to mention it, it used your code to test & benchmark my (minimal) implementation of Scheme https://github.com/twolodzko/gosch , the code landed in the examples directory, with a mention in README of the directory.

**Comment by bmitc** [comment]
Ah, interesting. Scheme is lovely! I don't know Go, but I've previously thought about picking up Thorsten Ball's books *Writing an Interpreter in Go* and *Writing a Compiler in Go*.

I'm surprised to see this repository used in that way, but I'm glad it was at least somewhat helpful.

**Comment by twolodzko** [comment]
"Writing an Interpreter in Go" is totally worth recommending. Thanks!
